import { mkdtemp, realpath, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { Project, SyntaxKind } from "ts-morph";
import { generate } from "ts-to-zod";
import { z } from "zod";
import type { ProviderOptionsSchemaEntry } from "../src/types";
import { type ProviderSchemaSource, providerSpecifier, readProviderSchemaCatalog } from "./provider-catalog";
import { extractProviderDeclaration } from "./provider-declaration";

const compare = (left: string, right: string) => (left < right ? -1 : left > right ? 1 : 0);

const stringProperty = (value: unknown, key: string) => {
  if (typeof value !== "object" || value === null) return undefined;
  const property = (value as Record<string, unknown>)[key];
  return typeof property === "string" ? property : undefined;
};

const readProviderPackage = async (packageRoot: string, subpath?: string) => {
  const value: unknown = await Bun.file(join(packageRoot, "package.json")).json();
  const version = stringProperty(value, "version");
  if (!version) throw new Error("Provider package metadata requires a version");
  const exportsValue =
    typeof value === "object" && value !== null ? (value as { exports?: unknown }).exports : undefined;
  const selectedExport =
    typeof exportsValue === "object" && exportsValue !== null
      ? (exportsValue as Record<string, unknown>)[subpath ? `./${subpath}` : "."]
      : undefined;
  const declarationEntry =
    stringProperty(selectedExport, "types") ??
    (subpath ? undefined : (stringProperty(value, "types") ?? stringProperty(value, "typings")));
  if (!declarationEntry) throw new Error("Provider package has no declaration entry");
  return { version, declarationEntry };
};

const resolveInstalledProviderSource = (rootPath: string, source: ProviderSchemaSource) =>
  realpath(join(rootPath, "node_modules", source.packageName));

const resolveDeclarationEntry = (packageRoot: string, declarationEntry: string) =>
  realpath(resolve(packageRoot, declarationEntry));

const sortValue = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(sortValue);
  if (typeof value !== "object" || value === null) return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => compare(left, right))
      .map(([key, item]) => [key, sortValue(item)]),
  );
};

const namespaceSource = (sourceText: string, index: number) => {
  const project = new Project({ useInMemoryFileSystem: true });
  const source = project.createSourceFile("provider.ts", sourceText);
  const declarations = [...source.getInterfaces(), ...source.getTypeAliases(), ...source.getEnums()];
  for (const node of [...declarations, ...source.getDescendantsOfKind(SyntaxKind.PropertySignature)]) {
    const jsDoc = node.getJsDocs().at(-1);
    if (!jsDoc) continue;
    const description = jsDoc.getDescription().trim();
    if (description && !jsDoc.getTags().some((tag) => tag.getTagName() === "description")) {
      jsDoc.addTag({ tagName: "description", text: description });
    }
  }
  const root = source.getTypeAliasOrThrow("ProviderOptions");
  for (const declaration of declarations) declaration.rename(`P${index}${declaration.getName()}`);
  return { sourceText: source.getFullText(), rootSchemaName: `${root.getName()}Schema` };
};

const schemaBody = (source: string) =>
  source.replace(/^\/\/ Generated by ts-to-zod\s+import \{ z \} from "zod";\s*/u, "").trim();

const removeDescriptionTags = (sourceText: string) => {
  const project = new Project({ useInMemoryFileSystem: true });
  const source = project.createSourceFile("schema.ts", sourceText);
  for (const jsDoc of source.getDescendantsOfKind(SyntaxKind.JSDoc)) {
    for (const tag of jsDoc.getTags().filter((item) => item.getTagName() === "description")) tag.remove();
    if (!jsDoc.getDescription().trim() && jsDoc.getTags().length === 0) jsDoc.remove();
  }
  return source.getFullText();
};

const schemaExpression = (source: ProviderSchemaSource, schemaName: string) => {
  const optional = source.overrides?.optional;
  if (!optional || optional.length === 0) return schemaName;
  return `${schemaName}.partial({ ${optional.map((name) => `${JSON.stringify(name)}: true`).join(", ")} }).meta(${schemaName}.meta() ?? {})`;
};

const evaluateZodMap = async (source: string) => {
  const zodUrl = pathToFileURL(Bun.resolveSync("zod", import.meta.dir)).href;
  const runnable = source.replace('from "zod"', `from ${JSON.stringify(zodUrl)}`);
  const javascript = new Bun.Transpiler({ loader: "ts" }).transformSync(runnable);
  const directory = await mkdtemp(join(tmpdir(), "provider-zod-"));
  const path = join(directory, "module.mjs");
  try {
    await Bun.write(path, javascript);
    const module = (await import(pathToFileURL(path).href)) as {
      readonly PROVIDER_OPTIONS_ZOD_SCHEMAS: Readonly<Record<string, z.ZodType>>;
    };
    return module.PROVIDER_OPTIONS_ZOD_SCHEMAS;
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
};

const renderJsonSource = (entries: Readonly<Record<string, ProviderOptionsSchemaEntry>>) =>
  [
    "// biome-ignore-all format: This file is deterministically generated.",
    'import type { ProviderOptionsSchemaEntry } from "./types.js";',
    "",
    `export const PROVIDER_OPTIONS_SCHEMAS: Readonly<Record<string, ProviderOptionsSchemaEntry>> = ${JSON.stringify(sortValue(entries), null, 2)};`,
    "",
  ].join("\n");

export const generateProviderArtifacts = async (rootPath: string) => {
  const sources = await readProviderSchemaCatalog(rootPath);
  const schemaSources: string[] = [];
  const mapEntries: string[] = [];
  const metadata: Array<{
    source: ProviderSchemaSource;
    packageVersion: string;
    warnings: Awaited<ReturnType<typeof extractProviderDeclaration>>["warnings"];
  }> = [];

  for (const [index, source] of sources.entries()) {
    const packageRoot = await realpath(await resolveInstalledProviderSource(rootPath, source));
    const packageMetadata = await readProviderPackage(packageRoot, source.subpath);
    const extracted = await extractProviderDeclaration({
      packageRoot,
      declarationEntry: await resolveDeclarationEntry(packageRoot, packageMetadata.declarationEntry),
      factoryName: source.factoryName,
    });
    const namespaced = namespaceSource(extracted.sourceText, index);
    const generated = generate({
      sourceText: namespaced.sourceText,
      getSchemaName: (name) => `${name}Schema`,
      keepComments: true,
    });
    if (generated.errors.length > 0) throw new Error(generated.errors.join("\n"));
    schemaSources.push(schemaBody(removeDescriptionTags(generated.getZodSchemasFile(""))));
    mapEntries.push(
      `  ${JSON.stringify(providerSpecifier(source))}: ${schemaExpression(source, namespaced.rootSchemaName)},`,
    );
    metadata.push({ source, packageVersion: packageMetadata.version, warnings: extracted.warnings });
  }

  const zodSource = [
    "// biome-ignore-all format: This file is deterministically generated.",
    'import { z } from "zod";',
    "",
    ...schemaSources,
    "",
    "export const PROVIDER_OPTIONS_ZOD_SCHEMAS: Readonly<Record<string, z.ZodType>> = {",
    ...mapEntries,
    "};",
    "",
  ].join("\n");
  const zodSchemas = await evaluateZodMap(zodSource);
  const entries: Record<string, ProviderOptionsSchemaEntry> = {};

  for (const item of metadata) {
    const specifier = providerSpecifier(item.source);
    const zodSchema = zodSchemas[specifier];
    if (!zodSchema) throw new Error(`Generated Zod schema is missing: ${specifier}`);
    if (
      zodSchema instanceof z.ZodObject &&
      item.source.overrides?.optional.some((name) => !(name in zodSchema.shape))
    ) {
      throw new Error(`Optional override does not match a provider option: ${specifier}`);
    }
    const schema = z.toJSONSchema(zodSchema, {
      unrepresentable: "any",
      io: "input",
      cycles: "ref",
      reused: "inline",
    }) as Record<string, unknown>;
    schema["additionalProperties"] = true;
    const properties = schema["properties"] as Record<string, unknown> | undefined;
    for (const warning of item.warnings) delete properties?.[warning.path];
    entries[specifier] = {
      packageName: specifier,
      packageVersion: item.packageVersion,
      factoryName: item.source.factoryName,
      schema,
      warnings: item.warnings,
    };
  }

  return {
    count: sources.length,
    zodSource,
    jsonSource: renderJsonSource(entries),
  };
};
